### ISSUE TITLE
Handing of diagnostics output more than cmdheight...

### ISSUE THREAD

**Issue by kting28** [seblj/nvim-echo-diagnostics#2]
Hi,

First of all great plugin ! I came from vim-lsp which does diagnostic echo natively but couldn't find a good way in neovim until I stumble upon this.

Question is that if the diagnostics is more than `cmdheight`, it seems to pause the editor :

![image](https://user-images.githubusercontent.com/24449116/155400429-8ab81ae7-9498-4882-b2b3-576f20f4be5a.png)

Here in this case whenever I land on the line, the "Press ENTER or type command to continue"  will show which is kind of annoying. Anyway to fix this?

**Comment by seblyng** [comment]
Hi, glad you like it! The plugin should consider the cmdheight, if you use:
```vim
autocmd CursorHold * lua require('echo-diagnostics').echo_line_diagnostic()
```

The function `echo_entire_diagnostic()` should prompt you with the press enter to continue. Do you use the `echo_line_diagnostic()`? If you do use this, it is a bug and I could try to fix it. I would need some example code, the language server and the options you have set from this plugin.

**Comment by kting28** [comment]
Yes I'm using `require('echo-diagnostics').echo_line_diagnostic()` in the `CursorHold`. I did some testing, if `cmdheight=1` the truncation does work. In the example above, the entire message has 3 lines and my `cmdheight` is 2 and somehow that doesn't work. This is from clangd on C code. I will need to craft an example. But may be I will just debug it a bit, the logic in `show_entire_diagnoistic` should have worked, will add some debug prints to see what's `height` and `#tbl` in this case. Will let you know.

**Comment by seblyng** [comment]
Okay thank you! This is then definetely a bug, and should be fixed!

**Comment by kting28** [comment]
Alright, I think I figured out why but the fix is probably not quick. Basically the truncation of message based on width of window is not handling multiple diagnostic items. The truncation is based on `#msg` which is the length of the flattened string divided by number of columns but in this case, one of the character in `msg` is a newline, so the truncation may or may not cut the message enough.

![image](https://user-images.githubusercontent.com/24449116/155419882-f3d80c2f-a349-45e3-86e9-3a017e776e39.png)
Above are some debug prints. `msg` is printed before and after the truncation. You can see the math is messed up and the `...` is simply attached to the original message.

Probably need to do the length limit per diagnostic item instead of applying it on the flattened `msg`

**Comment by seblyng** [comment]
Hmm okay... are you able to produce a code snippet I can use to reproduce the issue, so I also can look into it?

**Comment by kting28** [comment]
Sure, anything that produces 2 diagnostics in the same source line and one of the line being really long will trigger. E.g. using C code. Here the diagnostics are 1) `abc` is not an array 2) `bbb....` doesn't exist. I made the name really long so it doesn't fit the nvim window.
```
typedef struct {
    int abc;
  } test;

  int main() {

    test t;
    t.abc[100] = t.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  bbbbbbbbbbbbbbbbbbbbbbbbbbb;
  }
```
Output:
```
1: Subscripted value is not an array, pointer, or vector
2: No member named 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbb' in 'test'
Press ENTER or type command to continue
```

**Comment by kting28** [comment]
Here's my 1 line workaround for now. Essentially just replace `\n` with `|` in the `msg` so that the width based truncation works correctly. Not pretty, but at least consistent. I need something quick because I'm in the middle of a refactoring and there are lots of diagnostics :)
```
       -- Check width of mesasge
+      -- Remove newlines so length/columns math below works out
+      msg = string.gsub(msg, "\n", " | ")
        local winmargin = 20
        local windowlen = vim.api.nvim_get_option('columns')
        if (#msg / (windowlen - winmargin)) > height then
            -- Remove last part of message and add ' ...' to indicate that the msg is truncated
            msg = string.sub(msg, 1, (height * windowlen) - winmargin) .. ' ...'
        end
        return msg
```

**Comment by seblyng** [comment]
Thank you! I'll take a look at this today after work, and will hopefully find a consistent solution🙌
