### ISSUE TITLE
Handling of diagnostic messages with newlines 

### ISSUE THREAD

**Issue by kting28** [seblj/nvim-echo-diagnostics#6]
Hi @seblj 
Got another corner case here related to #2 
Your recent fix works well but I found language server for python `pyright` outputs diagnostics *containing* newlines; hence screwing up the height calculation again.

```python
  class foo:
      def __init__(self):
          self.a = 0
          self.b = 0

  s = foo()
  s.c = 2
```
In this example `s.c` doesn't exist and the error message from `pyright` looks like this:
![image](https://user-images.githubusercontent.com/24449116/157126400-c13d7d89-98a5-4aeb-824e-b1ebd9848f37.png)
Here the `cmdheight` is 2.
I think the newline *before* `Member` is part of the output. May be the plugin need to strip newlines before formatting?

**Comment by seblyng** [comment]
Thanks for the issue report! Yes that makes sense that there could be a newline at the end causing problems. Thanks for the minimal example also! I'll take a look at this first thing in the morning😄

**Comment by seblyng** [comment]
Hmm, are you sure you are using the latest version of the plugin? After I finished the PR, I found a bug with the newlines, and I handled that pretty fast after finishing the PR. I can't seem to reproduce the problem. @kting28

**Comment by seblyng** [comment]
While looking around and trying to recreate the bug I actually found an edge case where it would prompt you with the press enter to continue. I don't think this is related to this issue, but if you could pull the latest changes to see if you still have this problem, it would be awesome😄

**Comment by kting28** [comment]
My bad, after pulling latest can't reproduce the issue, I must have missed it earlier. Thanks for looking into it!

**Comment by seblyng** [comment]
No problem! Thanks for opening an issue!
